module IcInterperterExamples where

import ICInterpreter

{-  Tests

    To see  pretty-printed versions of these, type

        showICProgram icTest1

    etc.

    To run the programs, type

        execute icTest1

    etc. or

        debug 10000 icTest1

    etc.

-}

-- The numbering of tests corresponds to examples given in the project writeup.




icTest1 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "x") (Val' 6)),
   (Assign' (Var' "y") (Val' 8)),
   (Times' (Var' "_t1") (Var' "x") (Var' "y")),
   (Div' (Var' "_t1") (Var' "_t1") (Val' 3)),
   (Uminus' (Var' "_t2") (Var' "x")),
   (Plus' (Var' "_t2") (Var' "_t1") (Var' "_t2")),
   (Times' (Var' "_t1") (Val' 2) (Var' "y")),
   (Plus' (Var' "_t1") (Var' "_t2") (Var' "_t1")),
   (Assign' (Var' "z") (Var' "_t1")),
   (Minus' (Var' "_t1") (Var' "x") (Val' 2)),
   (Mod' (Var' "_t1") (Var' "x") (Var' "_t1")),
   (Minus' (Var' "_t1") (Var' "z") (Var' "_t1")),
   (Assign' (Var' "w") (Var' "_t1")),
   (Print' "w = " (Var' "w")),
   (Return' (Val' 0))  ]

icTest2 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "x") (Val' 4)),
   (Assign' (Var' "y") (Val' 2)),
   (Uminus' (Var' "_t1") (Val' 1)),
   (Assign' (Var' "z") (Var' "_t1")),
   (Gt' (Var' "_t1") (Var' "x") (Val' 2)),
   (Bzero'  (Var' "_t1") 11),
   (Jump' 10),
   (Print' "x = " (Var' "x")),
   (Lt' (Var' "_t2") (Var' "y") (Val' 2)),
   (Bzero'  (Var' "_t2") 15),
   (Jump' 14),
   (Print' "y = " (Var' "y")),
   (NotEq' (Var' "_t3") (Var' "z") (Val' 2)),
   (Bzero'  (Var' "_t3") 20),
   (Jump' 18),
   (Print' "z = " (Var' "z")),
   (Jump' 21),
   (Print' "y = " (Var' "y")),
   (Print' "z = " (Var' "z")),
   (Le' (Var' "_t4") (Var' "z") (Var' "y")),
   (Bzero'  (Var' "_t4") 34),
   (Jump' 25),
   (Print' "x = " (Var' "x")),
   (Plus' (Var' "_t5") (Var' "x") (Var' "y")),
   (Gt' (Var' "_t5") (Var' "_t5") (Var' "z")),
   (Bzero'  (Var' "_t5") 32),
   (Jump' 30),
   (Print' "y = " (Var' "y")),
   (Jump' 33),
   (Print' "z = " (Var' "z")),
   (Jump' 35),
   (Print' "z = " (Var' "z")),
   (Return' (Val' 0))  ]

icTest3 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "k") (Val' 1)),
   (Assign' (Var' "sum") (Val' 0)),
   (Le' (Var' "_t1") (Var' "k") (Val' 10)),
   (Bzero'  (Var' "_t1") 13),
   (Jump' 8),
   (Plus' (Var' "_t2") (Var' "sum") (Var' "k")),
   (Assign' (Var' "sum") (Var' "_t2")),
   (Plus' (Var' "_t2") (Var' "k") (Val' 1)),
   (Assign' (Var' "k") (Var' "_t2")),
   (Jump' 5),
   (Print' "sum = " (Var' "sum")),
   (Return' (Val' 0))  ]

icTest4 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "n") (Val' 1)),
   (Assign' (Var' "count") (Val' 0)),
   (Le' (Var' "_t1") (Var' "n") (Val' 3)),
   (Bzero'  (Var' "_t1") 24),
   (Jump' 8),
   (Assign' (Var' "m") (Val' 1)),
   (Le' (Var' "_t2") (Var' "m") (Val' 4)),
   (Bzero'  (Var' "_t2") 21),
   (Jump' 12),
   (Mod' (Var' "_t3") (Var' "m") (Var' "n")),
   (Equal' (Var' "_t3") (Var' "_t3") (Val' 0)),
   (Bzero'  (Var' "_t3") 18),
   (Jump' 16),
   (Plus' (Var' "_t4") (Var' "count") (Val' 1)),
   (Assign' (Var' "count") (Var' "_t4")),
   (Plus' (Var' "_t4") (Var' "m") (Val' 1)),
   (Assign' (Var' "m") (Var' "_t4")),
   (Jump' 9),
   (Plus' (Var' "_t4") (Var' "n") (Val' 1)),
   (Assign' (Var' "n") (Var' "_t4")),
   (Jump' 5),
   (Print' "count = " (Var' "count")),
   (Return' (Val' 0))  ]

icTest5 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "count") (Val' 0)),
   (Assign' (Var' "limit") (Val' 10)),
   (Assign' (Var' "n") (Val' 2)),
   (Le' (Var' "_t1") (Var' "count") (Var' "limit")),
   (Bzero'  (Var' "_t1") 31),
   (Jump' 9),
   (Assign' (Var' "isPrime") (Val' 1)),
   (Assign' (Var' "k") (Val' 2)),
   (Lt' (Var' "_t2") (Var' "k") (Var' "n")),
   (Bzero'  (Var' "_t2") 22),
   (Jump' 14),
   (Mod' (Var' "_t3") (Var' "n") (Var' "k")),
   (Equal' (Var' "_t3") (Var' "_t3") (Val' 0)),
   (Bzero'  (Var' "_t3") 19),
   (Jump' 18),
   (Assign' (Var' "isPrime") (Val' 0)),
   (Plus' (Var' "_t4") (Var' "k") (Val' 1)),
   (Assign' (Var' "k") (Var' "_t4")),
   (Jump' 11),
   (Equal' (Var' "_t4") (Var' "isPrime") (Val' 1)),
   (Bzero'  (Var' "_t4") 28),
   (Jump' 25),
   (Print' "n = " (Var' "n")),
   (Plus' (Var' "_t5") (Var' "count") (Val' 1)),
   (Assign' (Var' "count") (Var' "_t5")),
   (Plus' (Var' "_t5") (Var' "n") (Val' 1)),
   (Assign' (Var' "n") (Var' "_t5")),
   (Jump' 6),
   (Return' (Val' 0))  ]

icTest6 = [    (Push'),
   (Call' 3),
   (Halt'),
   (Assign' (Var' "x") (Val' 3)),
   (Assign' (Var' "y") (Val' 5)),
   (Assign' (Var' "z") (Val' 1)),
   (Gt' (Var' "_t1") (Var' "x") (Val' 2)),
   (Bzero'  (Var' "_t1") 13),
   (Jump' 9),
   (Lt' (Var' "_t2") (Var' "y") (Val' 5)),
   (Bzero'  (Var' "_t2") 13),
   (Jump' 12),
   (Print' "x = " (Var' "x")),
   (Gt' (Var' "_t3") (Var' "x") (Val' 2)),
   (Bzero'  (Var' "_t3") 16),
   (Jump' 19),
   (Lt' (Var' "_t4") (Var' "y") (Val' 5)),
   (Bzero'  (Var' "_t4") 20),
   (Jump' 19),
   (Print' "x = " (Var' "x")),
   (Gt' (Var' "_t5") (Var' "x") (Val' 2)),
   (Bzero'  (Var' "_t5") 26),
   (Jump' 23),
   (Lt' (Var' "_t6") (Var' "y") (Val' 5)),
   (Bzero'  (Var' "_t6") 26),
   (Jump' 29),
   (Equal' (Var' "_t7") (Var' "z") (Val' 2)),
   (Bzero'  (Var' "_t7") 29),
   (Jump' 30),
   (Print' "x = " (Var' "x")),
   (NotEq' (Var' "_t8") (Var' "z") (Val' 2)),
   (Bzero'  (Var' "_t8") 33),
   (Jump' 39),
   (Gt' (Var' "_t9") (Var' "x") (Val' 2)),
   (Bzero'  (Var' "_t9") 40),
   (Jump' 36),
   (Lt' (Var' "_t10") (Var' "y") (Val' 5)),
   (Bzero'  (Var' "_t10") 40),
   (Jump' 39),
   (Print' "x = " (Var' "x")),
   (Return' (Val' 0))  ]

icTest7 = [    (Push'),
   (Call' 8),
   (Halt'),
   (Plus' (Var' "_t1") (Var' "x") (Val' 1)),
   (Assign' (Var' "n") (Var' "_t1")),
   (Times' (Var' "_t1") (Var' "n") (Val' 2)),
   (Assign' (Var' "n") (Var' "_t1")),
   (Return' (Var' "n")),
   (Assign' (Var' "y") (Val' 2)),
   (Assign' (Var' "n") (Val' 3)),
   (Plus' (Var' "_t1") (Var' "y") (Var' "n")),
   (Push'),
   (Assign' (Var' "x") (Var' "_t1")),
   (Call' 3),
   (Assign' (Var' "_t2") (Var' "_ret_val")),
   (Assign' (Var' "z") (Var' "_t2")),
   (Print' "z = " (Var' "z")),
   (Return' (Val' 0))  ]

icTest8 = [  (Push'),
   (Call' 5),
   (Halt'),
   (Plus' (Var' "_t1") (Var' "x") (Val' 1)),
   (Return' (Var' "_t1")),
   (Assign' (Var' "a") (Val' 1)),
   (Push'),
   (Assign' (Var' "x") (Var' "a")),
   (Call' 3),
   (Assign' (Var' "_t2") (Var' "_ret_val")),
   (Plus' (Var' "_t3") (Var' "a") (Val' 1)),
   (Push'),
   (Assign' (Var' "x") (Var' "_t3")),
   (Call' 3),
   (Assign' (Var' "_t4") (Var' "_ret_val")),
   (Times' (Var' "_t5") (Var' "a") (Val' 2)),
   (Push'),
   (Assign' (Var' "x") (Var' "_t5")),
   (Call' 3),
   (Assign' (Var' "_t6") (Var' "_ret_val")),
   (Times' (Var' "_t6") (Var' "_t4") (Var' "_t6")),
   (Plus' (Var' "_t6") (Var' "_t2") (Var' "_t6")),
   (Assign' (Var' "z") (Var' "_t6")),
   (Print' "z = " (Var' "z")),
   (Return' (Val' 0))  ]

icTest9 = [    (Push'),
   (Call' 5),
   (Halt'),
   (Plus' (Var' "_t1") (Var' "x") (Val' 1)),
   (Return' (Var' "_t1")),
   (Assign' (Var' "a") (Val' 5)),
   (Push'),
   (Assign' (Var' "x") (Var' "a")),
   (Call' 3),
   (Assign' (Var' "_t2") (Var' "_ret_val")),
   (Push'),
   (Assign' (Var' "x") (Var' "_t2")),
   (Call' 3),
   (Assign' (Var' "_t3") (Var' "_ret_val")),
   (Push'),
   (Assign' (Var' "x") (Var' "_t3")),
   (Call' 3),
   (Assign' (Var' "_t4") (Var' "_ret_val")),
   (Assign' (Var' "z") (Var' "_t4")),
   (Print' "z = " (Var' "z")),
   (Return' (Val' 0))  ]

icTest10 =  [ (Push'),
   (Call' 18),
   (Halt'),
   (Plus' (Var' "_t1") (Var' "x") (Val' 1)),
   (Return' (Var' "_t1")),
   (Times' (Var' "_t2") (Var' "x") (Val' 2)),
   (Return' (Var' "_t2")),
   (Push'),
   (Assign' (Var' "x") (Var' "y")),
   (Call' 3),
   (Assign' (Var' "_t3") (Var' "_ret_val")),
   (Assign' (Var' "z") (Var' "_t3")),
   (Push'),
   (Assign' (Var' "x") (Var' "z")),
   (Call' 5),
   (Assign' (Var' "_t3") (Var' "_ret_val")),
   (Assign' (Var' "y") (Var' "_t3")),
   (Return' (Var' "y")),
   (Push'),
   (Assign' (Var' "y") (Val' 10)),
   (Call' 7),
   (Assign' (Var' "_t3") (Var' "_ret_val")),
   (Assign' (Var' "z") (Var' "_t3")),
   (Print' "z = " (Var' "z")),
   (Return' (Val' 0))  ]

icTest11 = [  (Push'),
   (Call' 13),
   (Halt'),
   (Assign' (Var' "a") (Val' 2854)),
   (NotEq' (Var' "_t1") (Var' "b") (Val' 0)),
   (Bzero' (Var' "_t1") 12),
   (Jump' 7),
   (Assign' (Var' "t") (Var' "b")),
   (Mod' (Var' "_t2") (Var' "a") (Var' "b")),
   (Assign' (Var' "b") (Var' "_t2")),
   (Assign' (Var' "a") (Var' "t")),
   (Jump' 4),
   (Return' (Var' "a")),
   (Assign' (Var' "m") (Val' 264)),
   (Push'),
   (Assign' (Var' "b") (Var' "m")),
   (Call' 3),
   (Assign' (Var' "_t2") (Var' "_ret_val")),
   (Assign' (Var' "res") (Var' "_t2")),
   (Print' "res = " (Var' "res")),
   (Return' (Val' 0))  ]

icTest12 = [    (Push'),
   (Call' 30),
   (Halt'),
   (Le' (Var' "_t1") (Var' "n") (Val' 2)),
   (Bzero' (Var' "_t1" ) 8),
   (Jump' 6),
   (Return' (Val' 1)),
   (Jump' 30),
   (Minus' (Var' "_t2") (Var' "n") (Val' 1)),
   (Push'),
   (Assign' (Var' "n") (Var' "_t2")),
   (Call' 3),
   (Assign' (Var' "_t3") (Var' "_ret_val")),
   (Minus' (Var' "_t3") (Var' "n") (Var' "_t3")),
   (Push'),
   (Assign' (Var' "n") (Var' "_t3")),
   (Call' 3),
   (Assign' (Var' "_t4") (Var' "_ret_val")),
   (Minus' (Var' "_t5") (Var' "n") (Val' 2)),
   (Push'),
   (Assign' (Var' "n") (Var' "_t5")),
   (Call' 3),
   (Assign' (Var' "_t6") (Var' "_ret_val")),
   (Minus' (Var' "_t6") (Var' "n") (Var' "_t6")),
   (Push'),
   (Assign' (Var' "n") (Var' "_t6")),
   (Call' 3),
   (Assign' (Var' "_t7") (Var' "_ret_val")),
   (Plus' (Var' "_t7") (Var' "_t4") (Var' "_t7")),
   (Return' (Var' "_t7")),
   (Assign' (Var' "k") (Val' 1)),
   (Lt' (Var' "_t4") (Var' "k") (Val' 20)),
   (Bzero' (Var' "_t4" ) 43),
   (Jump' 34),
   (Push'),
   (Assign' (Var' "n") (Var' "k")),
   (Call' 3),
   (Assign' (Var' "_t8") (Var' "_ret_val")),
   (Assign' (Var' "q") (Var' "_t8")),
   (Print' "q = " (Var' "q")),
   (Plus' (Var' "_t8") (Var' "k") (Val' 1)),
   (Assign' (Var' "k") (Var' "_t8")),
   (Jump' 31),
   (Return' (Val' 0)) ]

