module AnnoyingLists(AnnoyingList(), fromList, AnnoyingLists.map, AnnoyingLists.foldr,  AnnoyingLists.filter) where  -- DO NOT EDIT THIS FILE


data AnnoyingList a = Annoying [a] deriving Show


fromList :: [a] -> AnnoyingList a
fromList x = Annoying x

map :: (a->b) -> AnnoyingList a -> AnnoyingList b
map f (Annoying x) = Annoying $ Prelude.map f x


foldr :: (a->b->b) -> b -> AnnoyingList a -> b
foldr f start (Annoying x) = Prelude.foldr f start x



filter :: (a-> Bool) -> AnnoyingList a -> AnnoyingList a 
filter f (Annoying x) =  Annoying $ Prelude.filter f  x